---
# Config per OS — data, bukan logika.
# Pin ke nama versi (immutable). Jangan pakai -latest — race: CHECKSUM vs image bisa beda hash.
image_url: https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-9.8-20260526.x86_64.qcow2
checksum_url: https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/CHECKSUM
checksum_algorithm: sha256
checksum_file: CHECKSUM
image_file: AlmaLinux-9-GenericCloud-9.8-20260526.x86_64.qcow2

repo_dest_dir: /etc/yum.repos.d/
repo_filename: local.repo
repo_disable_cmd: "sed -i \"s/enabled=1/enabled=0/\" /etc/yum.repos.d/*.repo"

repo_file_content: |
  [baseos]
  name=AlmaLinux $releasever - BaseOS (local)
  baseurl=https://mirror.biznetgio.com/almalinux/9/BaseOS/x86_64/os/
  enabled=1
  gpgcheck=1
  gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9

  [appstream]
  name=AlmaLinux $releasever - AppStream (local)
  baseurl=https://mirror.biznetgio.com/almalinux/9/AppStream/x86_64/os/
  enabled=1
  gpgcheck=1
  gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9

update_cmd: "dnf -y update && dnf -y autoremove && dnf clean all"
